// <auto-generated />
using System;
using ECommerce.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.EntityFramework.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ECommerce.Data.Models.Categories", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByCategoriesId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedCategoriesId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByCategoriesId");

                    b.HasIndex("UpdatedCategoriesId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ECommerce.Data.Models.Categories", b =>
                {
                    b.HasOne("ECommerce.Data.Models.Categories", "CreatedByCategories")
                        .WithMany()
                        .HasForeignKey("CreatedByCategoriesId");

                    b.HasOne("ECommerce.Data.Models.Categories", "UpdatedByCategories")
                        .WithMany()
                        .HasForeignKey("UpdatedCategoriesId");

                    b.Navigation("CreatedByCategories");

                    b.Navigation("UpdatedByCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
